source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Yanyuxxxx/YURepo.git'

platform :ios, '8.0'
inhibit_all_warnings!

target 'YUKitDemo' do
    
    pod 'YUKit', '0.1.1'
    
end
